/* tslint:disable */
/* eslint-disable */
/**
 * ExerciseApi
 * A web API for getting info about exercises and workouts
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: chlaferney@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum Equipment {
    BalanceBoard = 'balance board',
    Bar = 'bar',
    Barbell = 'barbell',
    Bench = 'bench',
    Body = 'body',
    BosuBall = 'bosu ball',
    Cable = 'cable',
    Dumbbells = 'dumbbells',
    ExerciseBall = 'exercise ball',
    ExerciseBand = 'exercise band',
    MedicineBall = 'medicine ball',
    ParallelBars = 'parallel bars',
    PullUpBar = 'pull-up bar',
    SmithMachine = 'smith machine',
    TBarMachine = 't-bar machine',
    Towel = 'towel',
    VBar = 'v-bar',
    WeightPlate = 'weight plate',
    WideBar = 'wide bar',
    BenchDecline = 'bench: decline',
    BenchHyperextension = 'bench: hyperextension',
    BenchIncline = 'bench: incline',
    MachineAbductor = 'machine: abductor',
    MachineAdductor = 'machine: adductor',
    MachineBenchPress = 'machine: bench press',
    MachineBicepCurl = 'machine: bicep curl',
    MachineButterfly = 'machine: butterfly',
    MachineCalfRaise = 'machine: calf raise',
    MachineChest = 'machine: chest',
    MachineHackSquat = 'machine: hack squat',
    MachineLegCurl = 'machine: leg curl',
    MachineLegExtension = 'machine: leg extension',
    MachineLegPress = 'machine: leg press',
    MachineShoulderPress = 'machine: shoulder press',
    MachineTricepDip = 'machine: tricep dip',
    MachineTricepExtension = 'machine: tricep extension'
}

export function EquipmentFromJSON(json: any): Equipment {
    return EquipmentFromJSONTyped(json, false);
}

export function EquipmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Equipment {
    return json as Equipment;
}

export function EquipmentToJSON(value?: Equipment | null): any {
    return value as any;
}

