/* tslint:disable */
/* eslint-disable */
/**
 * ExerciseApi
 * A web API for getting info about exercises and workouts
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: chlaferney@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExerciseImages
 */
export interface ExerciseImages {
    /**
     * 
     * @type {Array<string>}
     * @memberof ExerciseImages
     */
    png?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExerciseImages
     */
    svg?: Array<string>;
}

export function ExerciseImagesFromJSON(json: any): ExerciseImages {
    return ExerciseImagesFromJSONTyped(json, false);
}

export function ExerciseImagesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExerciseImages {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'png': !exists(json, 'png') ? undefined : json['png'],
        'svg': !exists(json, 'svg') ? undefined : json['svg'],
    };
}

export function ExerciseImagesToJSON(value?: ExerciseImages | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'png': value.png,
        'svg': value.svg,
    };
}


