/* tslint:disable */
/* eslint-disable */
/**
 * ExerciseApi
 * A web API for getting info about exercises and workouts
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: chlaferney@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExerciseMuscles
 */
export interface ExerciseMuscles {
    /**
     * 
     * @type {Array<string>}
     * @memberof ExerciseMuscles
     */
    primary?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExerciseMuscles
     */
    secondary?: Array<string>;
}

export function ExerciseMusclesFromJSON(json: any): ExerciseMuscles {
    return ExerciseMusclesFromJSONTyped(json, false);
}

export function ExerciseMusclesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExerciseMuscles {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'primary': !exists(json, 'primary') ? undefined : json['primary'],
        'secondary': !exists(json, 'secondary') ? undefined : json['secondary'],
    };
}

export function ExerciseMusclesToJSON(value?: ExerciseMuscles | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'primary': value.primary,
        'secondary': value.secondary,
    };
}


