/* tslint:disable */
/* eslint-disable */
/**
 * ExerciseApi
 * A web API for getting info about exercises and workouts
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: chlaferney@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ExerciseImages,
    ExerciseImagesFromJSON,
    ExerciseImagesFromJSONTyped,
    ExerciseImagesToJSON,
    ExerciseMuscles,
    ExerciseMusclesFromJSON,
    ExerciseMusclesFromJSONTyped,
    ExerciseMusclesToJSON,
} from './';

/**
 * 
 * @export
 * @interface Exercise
 */
export interface Exercise {
    /**
     * 
     * @type {number}
     * @memberof Exercise
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Exercise
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof Exercise
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Exercise
     */
    type?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Exercise
     */
    equipment?: Array<string>;
    /**
     * 
     * @type {ExerciseMuscles}
     * @memberof Exercise
     */
    muscles?: ExerciseMuscles;
    /**
     * 
     * @type {ExerciseImages}
     * @memberof Exercise
     */
    images?: ExerciseImages;
}

export function ExerciseFromJSON(json: any): Exercise {
    return ExerciseFromJSONTyped(json, false);
}

export function ExerciseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Exercise {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'equipment': !exists(json, 'equipment') ? undefined : json['equipment'],
        'muscles': !exists(json, 'muscles') ? undefined : ExerciseMusclesFromJSON(json['muscles']),
        'images': !exists(json, 'images') ? undefined : ExerciseImagesFromJSON(json['images']),
    };
}

export function ExerciseToJSON(value?: Exercise | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'title': value.title,
        'description': value.description,
        'type': value.type,
        'equipment': value.equipment,
        'muscles': ExerciseMusclesToJSON(value.muscles),
        'images': ExerciseImagesToJSON(value.images),
    };
}


