/* tslint:disable */
/* eslint-disable */
/**
 * ExerciseApi
 * A web API for getting info about exercises and workouts
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: chlaferney@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse400
 */
export interface InlineResponse400 {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse400
     */
    message?: string;
}

export function InlineResponse400FromJSON(json: any): InlineResponse400 {
    return InlineResponse400FromJSONTyped(json, false);
}

export function InlineResponse400FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse400 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function InlineResponse400ToJSON(value?: InlineResponse400 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}


