/* tslint:disable */
/* eslint-disable */
/**
 * ExerciseApi
 * A web API for getting info about exercises and workouts
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: chlaferney@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum MuscleGroup {
    Abs = 'abs',
    Arms = 'arms',
    Back = 'back',
    Buttocks = 'buttocks',
    Chest = 'chest',
    Legs = 'legs',
    Shoulders = 'shoulders'
}

export function MuscleGroupFromJSON(json: any): MuscleGroup {
    return MuscleGroupFromJSONTyped(json, false);
}

export function MuscleGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): MuscleGroup {
    return json as MuscleGroup;
}

export function MuscleGroupToJSON(value?: MuscleGroup | null): any {
    return value as any;
}

